/**
 * Lethean VPN Api
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificatesEntity model module.
 * @module model/CertificatesEntity
 * @version 1
 */
class CertificatesEntity {
    /**
     * Constructs a new <code>CertificatesEntity</code>.
     * @alias module:model/CertificatesEntity
     * @param id {Number} ID only
     */
    constructor(id) { 
        
        CertificatesEntity.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>CertificatesEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificatesEntity} obj Optional instance to populate.
     * @return {module:model/CertificatesEntity} The populated <code>CertificatesEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificatesEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * ID only
 * @member {Number} id
 */
CertificatesEntity.prototype['id'] = undefined;






export default CertificatesEntity;

