/**
 * Lethean VPN Api
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProxySettingsEntity model module.
 * @module model/ProxySettingsEntity
 * @version 1
 */
class ProxySettingsEntity {
    /**
     * Constructs a new <code>ProxySettingsEntity</code>.
     * @alias module:model/ProxySettingsEntity
     * @param endpoint {String} IP Address of endpoints for Proxy service only
     * @param port {String} Port available on endpoint
     * @param terms {String} Terms for the service
     * @param policy {Array.<String>} a JSON containing access policy - whitelist/blacklist default, allowed/blocked IPs and FQDNs in regex format. This is NOT sent to SDP. It is used by the Dispatcher to orchestrate restrictions on Server
     */
    constructor(endpoint, port, terms, policy) { 
        
        ProxySettingsEntity.initialize(this, endpoint, port, terms, policy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, endpoint, port, terms, policy) { 
        obj['endpoint'] = endpoint;
        obj['port'] = port;
        obj['terms'] = terms;
        obj['policy'] = policy;
    }

    /**
     * Constructs a <code>ProxySettingsEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProxySettingsEntity} obj Optional instance to populate.
     * @return {module:model/ProxySettingsEntity} The populated <code>ProxySettingsEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProxySettingsEntity();

            if (data.hasOwnProperty('endpoint')) {
                obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'String');
            }
            if (data.hasOwnProperty('terms')) {
                obj['terms'] = ApiClient.convertToType(data['terms'], 'String');
            }
            if (data.hasOwnProperty('policy')) {
                obj['policy'] = ApiClient.convertToType(data['policy'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * IP Address of endpoints for Proxy service only
 * @member {String} endpoint
 */
ProxySettingsEntity.prototype['endpoint'] = undefined;

/**
 * Port available on endpoint
 * @member {String} port
 */
ProxySettingsEntity.prototype['port'] = undefined;

/**
 * Terms for the service
 * @member {String} terms
 */
ProxySettingsEntity.prototype['terms'] = undefined;

/**
 * a JSON containing access policy - whitelist/blacklist default, allowed/blocked IPs and FQDNs in regex format. This is NOT sent to SDP. It is used by the Dispatcher to orchestrate restrictions on Server
 * @member {Array.<String>} policy
 */
ProxySettingsEntity.prototype['policy'] = undefined;






export default ProxySettingsEntity;

