/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProxySettingsEntity { 
    /**
     * IP Address of endpoints for Proxy service only
     */
    endpoint: string;
    /**
     * Port available on endpoint
     */
    port: string;
    /**
     * Terms for the service
     */
    terms: string;
    /**
     * a JSON containing access policy - whitelist/blacklist default, allowed/blocked IPs and FQDNs in regex format. This is NOT sent to SDP. It is used by the Dispatcher to orchestrate restrictions on Server
     */
    policy: Array<string>;
}

