/**
 * Lethean VPN Api
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimeRangeEntity { 
    /**
     * YYYY-MM-DDT00:00:00Z
     */
    from: string;
    /**
     * YYYY-MM-DDT00:00:00Z
     */
    to: string;
}

