/**
 * Lethean Explorer API
 * Lethean chain explorer API
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TxnEntity } from './txnEntity';


export interface BlockEntity { 
    block_height: number;
    current_height: number;
    hash: string;
    size: number;
    timestamp: number;
    timestamp_utc: string;
    txs: Array<TxnEntity>;
}

