/**
 * Lethean Explorer API
 * Lethean chain explorer API
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockOutputsEntity } from './blockOutputsEntity';


export interface BlockOutputEntity { 
    address: string;
    height: number;
    limit: number;
    mempool: boolean;
    outputs: Array<BlockOutputsEntity>;
    viewkey: string;
}

