/**
 * Lethean Explorer API
 * Lethean chain explorer API
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RawBlockMinerVout } from './rawBlockMinerVout';
import { RawBlockMinerVin } from './rawBlockMinerVin';
import { RctSigEntity } from './rctSigEntity';


export interface RawBlockMinerTx { 
    extra: Array<number>;
    rct_signatures: RctSigEntity;
    unlock_time: number;
    version: number;
    vin?: Array<RawBlockMinerVin>;
    vout?: Array<RawBlockMinerVout>;
}

