/**
 * Lethean Explorer API
 * Lethean chain explorer API
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RawTransactionEntityVin } from './rawTransactionEntityVin';
import { RawTransactionEntityVout } from './rawTransactionEntityVout';
import { RctSigPrunable } from './rctSigPrunable';
import { RawTransactionRctSignature } from './rawTransactionRctSignature';


export interface RawTransactionEntity { 
    extra: Array<string>;
    rct_signatures: RawTransactionRctSignature;
    rctsig_prunable: RctSigPrunable;
    unlock_time: number;
    version: number;
    vin: Array<RawTransactionEntityVin>;
    vout: Array<RawTransactionEntityVout>;
}

