// tslint:disable
/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface VpnSettingsEntity
 */
export interface VpnSettingsEntity {
    /**
     * IP Addresses of endpoints for VPN service only
     * @type {string}
     * @memberof VpnSettingsEntity
     */
    endpoint: string;
    /**
     * Port these settings apply to
     * @type {string}
     * @memberof VpnSettingsEntity
     */
    port: string;
    /**
     * mtu size parameter for vpn service only
     * @type {string}
     * @memberof VpnSettingsEntity
     */
    parameters: string;
    /**
     * Terms for the service
     * @type {string}
     * @memberof VpnSettingsEntity
     */
    terms: string;
    /**
     * a JSON containing access policy - whitelist/blacklist default, allowed/blocked IPs and FQDNs in regex format. This is NOT sent to SDP. It is used by the Dispatcher to orchestrate restrictions on Server
     * @type {Array<string>}
     * @memberof VpnSettingsEntity
     */
    policy: Array<string>;
}
