/**
 * LetheanVPN
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class FeedbackEntity {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("provider")
  private String provider = null;
  @SerializedName("services")
  private String services = null;
  @SerializedName("speed")
  private BigDecimal speed = null;
  @SerializedName("stability")
  private BigDecimal stability = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getProvider() {
    return provider;
  }
  public void setProvider(String provider) {
    this.provider = provider;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getServices() {
    return services;
  }
  public void setServices(String services) {
    this.services = services;
  }

  /**
   * minimum: 0
   * maximum: 5
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getSpeed() {
    return speed;
  }
  public void setSpeed(BigDecimal speed) {
    this.speed = speed;
  }

  /**
   * minimum: 0
   * maximum: 5
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getStability() {
    return stability;
  }
  public void setStability(BigDecimal stability) {
    this.stability = stability;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedbackEntity feedbackEntity = (FeedbackEntity) o;
    return (this.id == null ? feedbackEntity.id == null : this.id.equals(feedbackEntity.id)) &&
        (this.provider == null ? feedbackEntity.provider == null : this.provider.equals(feedbackEntity.provider)) &&
        (this.services == null ? feedbackEntity.services == null : this.services.equals(feedbackEntity.services)) &&
        (this.speed == null ? feedbackEntity.speed == null : this.speed.equals(feedbackEntity.speed)) &&
        (this.stability == null ? feedbackEntity.stability == null : this.stability.equals(feedbackEntity.stability));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.provider == null ? 0: this.provider.hashCode());
    result = 31 * result + (this.services == null ? 0: this.services.hashCode());
    result = 31 * result + (this.speed == null ? 0: this.speed.hashCode());
    result = 31 * result + (this.stability == null ? 0: this.stability.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedbackEntity {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  provider: ").append(provider).append("\n");
    sb.append("  services: ").append(services).append("\n");
    sb.append("  speed: ").append(speed).append("\n");
    sb.append("  stability: ").append(stability).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
