/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LTHNTimeRangeEntity.h
 *
 * 
 */

#ifndef LTHNTimeRangeEntity_H
#define LTHNTimeRangeEntity_H

#include <QJsonObject>

#include <QDateTime>

#include "LTHNEnum.h"
#include "LTHNObject.h"

namespace lthn {
namespace vpm {
namespace client {

class LTHNTimeRangeEntity : public LTHNObject {
public:
    LTHNTimeRangeEntity();
    LTHNTimeRangeEntity(QString json);
    ~LTHNTimeRangeEntity() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QDateTime getFrom() const;
    void setFrom(const QDateTime &from);
    bool is_from_Set() const;
    bool is_from_Valid() const;

    QDateTime getTo() const;
    void setTo(const QDateTime &to);
    bool is_to_Set() const;
    bool is_to_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QDateTime from;
    bool m_from_isSet;
    bool m_from_isValid;

    QDateTime to;
    bool m_to_isSet;
    bool m_to_isValid;
};

} // namespace lthn
} // namespace vpm
} // namespace client

Q_DECLARE_METATYPE(lthn::vpm::client::LTHNTimeRangeEntity)

#endif // LTHNTimeRangeEntity_H
