/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LTHNCertificatesEntity.h
 *
 * 
 */

#ifndef LTHNCertificatesEntity_H
#define LTHNCertificatesEntity_H

#include <QJsonObject>


#include "LTHNEnum.h"
#include "LTHNObject.h"

namespace lthn {
namespace vpm {
namespace client {

class LTHNCertificatesEntity : public LTHNObject {
public:
    LTHNCertificatesEntity();
    LTHNCertificatesEntity(QString json);
    ~LTHNCertificatesEntity() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getId() const;
    void setId(const double &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double id;
    bool m_id_isSet;
    bool m_id_isValid;
};

} // namespace lthn
} // namespace vpm
} // namespace client

Q_DECLARE_METATYPE(lthn::vpm::client::LTHNCertificatesEntity)

#endif // LTHNCertificatesEntity_H
