/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef LTHN_ENUM_H
#define LTHN_ENUM_H

#include <QJsonValue>
#include <QMetaType>
#include <QString>

namespace lthn {
namespace vpm {
namespace client {

class LTHNEnum {
public:
    LTHNEnum() {}

    LTHNEnum(QString jsonString) {
        fromJson(jsonString);
    }

    virtual ~LTHNEnum() {}

    virtual QJsonValue asJsonValue() const {
        return QJsonValue(jstr);
    }

    virtual QString asJson() const {
        return jstr;
    }

    virtual void fromJson(QString jsonString) {
        jstr = jsonString;
    }

    virtual void fromJsonValue(QJsonValue jval) {
        jstr = jval.toString();
    }

    virtual bool isSet() const {
        return false;
    }

    virtual bool isValid() const {
        return true;
    }

private:
    QString jstr;
};

} // namespace lthn
} // namespace vpm
} // namespace client

Q_DECLARE_METATYPE(lthn::vpm::client::LTHNEnum)

#endif // LTHN_ENUM_H
