/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LTHNServiceEntity.h
 *
 * 
 */

#ifndef LTHNServiceEntity_H
#define LTHNServiceEntity_H

#include <QJsonObject>

#include "LTHNCertificatesEntity.h"
#include "LTHNProxySettingsEntity.h"
#include "LTHNTimeRangeEntity.h"
#include "LTHNVpnSettingsEntity.h"
#include <QList>
#include <QString>

#include "LTHNEnum.h"
#include "LTHNObject.h"

namespace lthn {
namespace vpm {
namespace client {

class LTHNServiceEntity : public LTHNObject {
public:
    LTHNServiceEntity();
    LTHNServiceEntity(QString json);
    ~LTHNServiceEntity() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getType() const;
    void setType(const QString &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    QString getCost() const;
    void setCost(const QString &cost);
    bool is_cost_Set() const;
    bool is_cost_Valid() const;

    double getFirstPrePaidMinutes() const;
    void setFirstPrePaidMinutes(const double &first_pre_paid_minutes);
    bool is_first_pre_paid_minutes_Set() const;
    bool is_first_pre_paid_minutes_Valid() const;

    double getFirstVerificationsNeeded() const;
    void setFirstVerificationsNeeded(const double &first_verifications_needed);
    bool is_first_verifications_needed_Set() const;
    bool is_first_verifications_needed_Valid() const;

    double getSubsequentPrePaidMinutes() const;
    void setSubsequentPrePaidMinutes(const double &subsequent_pre_paid_minutes);
    bool is_subsequent_pre_paid_minutes_Set() const;
    bool is_subsequent_pre_paid_minutes_Valid() const;

    double getSubsequentVerificationsNeeded() const;
    void setSubsequentVerificationsNeeded(const double &subsequent_verifications_needed);
    bool is_subsequent_verifications_needed_Set() const;
    bool is_subsequent_verifications_needed_Valid() const;

    bool isAllowRefunds() const;
    void setAllowRefunds(const bool &allow_refunds);
    bool is_allow_refunds_Set() const;
    bool is_allow_refunds_Valid() const;

    double getDownloadSpeed() const;
    void setDownloadSpeed(const double &download_speed);
    bool is_download_speed_Set() const;
    bool is_download_speed_Valid() const;

    double getUploadSpeed() const;
    void setUploadSpeed(const double &upload_speed);
    bool is_upload_speed_Set() const;
    bool is_upload_speed_Valid() const;

    QList<LTHNProxySettingsEntity> getProxy() const;
    void setProxy(const QList<LTHNProxySettingsEntity> &proxy);
    bool is_proxy_Set() const;
    bool is_proxy_Valid() const;

    QList<LTHNVpnSettingsEntity> getVpn() const;
    void setVpn(const QList<LTHNVpnSettingsEntity> &vpn);
    bool is_vpn_Set() const;
    bool is_vpn_Valid() const;

    LTHNTimeRangeEntity getValidity() const;
    void setValidity(const LTHNTimeRangeEntity &validity);
    bool is_validity_Set() const;
    bool is_validity_Valid() const;

    bool isDisable() const;
    void setDisable(const bool &disable);
    bool is_disable_Set() const;
    bool is_disable_Valid() const;

    QList<LTHNCertificatesEntity> getCertificates() const;
    void setCertificates(const QList<LTHNCertificatesEntity> &certificates);
    bool is_certificates_Set() const;
    bool is_certificates_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString type;
    bool m_type_isSet;
    bool m_type_isValid;

    QString cost;
    bool m_cost_isSet;
    bool m_cost_isValid;

    double first_pre_paid_minutes;
    bool m_first_pre_paid_minutes_isSet;
    bool m_first_pre_paid_minutes_isValid;

    double first_verifications_needed;
    bool m_first_verifications_needed_isSet;
    bool m_first_verifications_needed_isValid;

    double subsequent_pre_paid_minutes;
    bool m_subsequent_pre_paid_minutes_isSet;
    bool m_subsequent_pre_paid_minutes_isValid;

    double subsequent_verifications_needed;
    bool m_subsequent_verifications_needed_isSet;
    bool m_subsequent_verifications_needed_isValid;

    bool allow_refunds;
    bool m_allow_refunds_isSet;
    bool m_allow_refunds_isValid;

    double download_speed;
    bool m_download_speed_isSet;
    bool m_download_speed_isValid;

    double upload_speed;
    bool m_upload_speed_isSet;
    bool m_upload_speed_isValid;

    QList<LTHNProxySettingsEntity> proxy;
    bool m_proxy_isSet;
    bool m_proxy_isValid;

    QList<LTHNVpnSettingsEntity> vpn;
    bool m_vpn_isSet;
    bool m_vpn_isValid;

    LTHNTimeRangeEntity validity;
    bool m_validity_isSet;
    bool m_validity_isValid;

    bool disable;
    bool m_disable_isSet;
    bool m_disable_isValid;

    QList<LTHNCertificatesEntity> certificates;
    bool m_certificates_isSet;
    bool m_certificates_isValid;
};

} // namespace lthn
} // namespace vpm
} // namespace client

Q_DECLARE_METATYPE(lthn::vpm::client::LTHNServiceEntity)

#endif // LTHNServiceEntity_H
