/**
 * Lethean VPN Api
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LetheanVpnApi);
  }
}(this, function(expect, LetheanVpnApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LetheanVpnApi.ServiceEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceEntity', function() {
    it('should create an instance of ServiceEntity', function() {
      // uncomment below and update the code to test ServiceEntity
      //var instane = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be.a(LetheanVpnApi.ServiceEntity);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property cost (base name: "cost")', function() {
      // uncomment below and update the code to test the property cost
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property firstPrePaidMinutes (base name: "firstPrePaidMinutes")', function() {
      // uncomment below and update the code to test the property firstPrePaidMinutes
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property firstVerificationsNeeded (base name: "firstVerificationsNeeded")', function() {
      // uncomment below and update the code to test the property firstVerificationsNeeded
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property subsequentPrePaidMinutes (base name: "subsequentPrePaidMinutes")', function() {
      // uncomment below and update the code to test the property subsequentPrePaidMinutes
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property subsequentVerificationsNeeded (base name: "subsequentVerificationsNeeded")', function() {
      // uncomment below and update the code to test the property subsequentVerificationsNeeded
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property allowRefunds (base name: "allowRefunds")', function() {
      // uncomment below and update the code to test the property allowRefunds
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property downloadSpeed (base name: "downloadSpeed")', function() {
      // uncomment below and update the code to test the property downloadSpeed
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property uploadSpeed (base name: "uploadSpeed")', function() {
      // uncomment below and update the code to test the property uploadSpeed
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property proxy (base name: "proxy")', function() {
      // uncomment below and update the code to test the property proxy
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property vpn (base name: "vpn")', function() {
      // uncomment below and update the code to test the property vpn
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property validity (base name: "validity")', function() {
      // uncomment below and update the code to test the property validity
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property disable (base name: "disable")', function() {
      // uncomment below and update the code to test the property disable
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

    it('should have the property certificates (base name: "certificates")', function() {
      // uncomment below and update the code to test the property certificates
      //var instance = new LetheanVpnApi.ServiceEntity();
      //expect(instance).to.be();
    });

  });

}));
