{-
   Lethean VPN Api
   Distributed Virtual Private Marketplace

   The version of the OpenAPI document: 1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Services exposing
    ( create
    , findOne
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



create : Api.Data.ServiceEntity -> Api.Request Api.Data.ServiceEntity
create serviceEntity_body =
    Api.request
        "POST"
        "/v1/service/add"
        []
        []
        []
        (Just (Api.Data.encodeServiceEntity serviceEntity_body))
        Api.Data.serviceEntityDecoder



findOne : String -> Api.Request String
findOne client_path =
    Api.request
        "GET"
        "/v1/service/search/{client}"
        [ ( "client", identity client_path ) ]
        []
        []
        Nothing
        Json.Decode.string
