/*
 * Lethean VPN Api
 *
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeRangeEntity {
    /// YYYY-MM-DDT00:00:00Z
    #[serde(rename = "from")]
    pub from: String,
    /// YYYY-MM-DDT00:00:00Z
    #[serde(rename = "to")]
    pub to: String,
}

impl TimeRangeEntity {
    pub fn new(from: String, to: String) -> TimeRangeEntity {
        TimeRangeEntity {
            from,
            to,
        }
    }
}


