=begin
#Lethean VPN Api

#Distributed Virtual Private Marketplace

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/certificates_entity'
require 'openapi_client/models/proxy_settings_entity'
require 'openapi_client/models/service_entity'
require 'openapi_client/models/time_range_entity'
require 'openapi_client/models/vpn_settings_entity'

# APIs
require 'openapi_client/api/default_api'
require 'openapi_client/api/provider_api'
require 'openapi_client/api/services_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
