#
# Lethean VPM
# Distributed Virtual Private Marketplace
# Version: 1
# Contact: contact@lethean.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CertificatesEntity' {
    Context 'CertificatesEntity' {
        It 'Initialize-CertificatesEntity' {
            # a simple test to create an object
            #$NewObject = Initialize-CertificatesEntity -Id "TEST_VALUE"
            #$NewObject | Should -BeOfType CertificatesEntity
            #$NewObject.property | Should -Be 0
        }
    }
}
