#
# Lethean VPN Api
# Distributed Virtual Private Marketplace
# Version: 1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProxySettingsEntity' {
    Context 'ProxySettingsEntity' {
        It 'Initialize-ProxySettingsEntity' {
            # a simple test to create an object
            #$NewObject = Initialize-ProxySettingsEntity -Endpoint "TEST_VALUE" -Port "TEST_VALUE" -Terms "TEST_VALUE" -Policy "TEST_VALUE"
            #$NewObject | Should -BeOfType ProxySettingsEntity
            #$NewObject.property | Should -Be 0
        }
    }
}
