#
# Lethean VPN Api
# Distributed Virtual Private Marketplace
# Version: 1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ServiceEntity' {
    Context 'ServiceEntity' {
        It 'Initialize-ServiceEntity' {
            # a simple test to create an object
            #$NewObject = Initialize-ServiceEntity -Id "TEST_VALUE" -Name "TEST_VALUE" -Type "TEST_VALUE" -Cost "TEST_VALUE" -FirstPrePaidMinutes "TEST_VALUE" -FirstVerificationsNeeded "TEST_VALUE" -SubsequentPrePaidMinutes "TEST_VALUE" -SubsequentVerificationsNeeded "TEST_VALUE" -AllowRefunds "TEST_VALUE" -DownloadSpeed "TEST_VALUE" -UploadSpeed "TEST_VALUE" -Proxy "TEST_VALUE" -Vpn "TEST_VALUE" -Validity "TEST_VALUE" -Disable "TEST_VALUE" -Certificates "TEST_VALUE"
            #$NewObject | Should -BeOfType ServiceEntity
            #$NewObject.property | Should -Be 0
        }
    }
}
