#
# Lethean VPM
# Distributed Virtual Private Marketplace
# Version: 1
# Contact: contact@lethean.io
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TimeRangeEntity' {
    Context 'TimeRangeEntity' {
        It 'Initialize-TimeRangeEntity' {
            # a simple test to create an object
            #$NewObject = Initialize-TimeRangeEntity -VarFrom "TEST_VALUE" -To "TEST_VALUE"
            #$NewObject | Should -BeOfType TimeRangeEntity
            #$NewObject.property | Should -Be 0
        }
    }
}
