#
# Lethean VPN Api
# Distributed Virtual Private Marketplace
# Version: 1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'VpnSettingsEntity' {
    Context 'VpnSettingsEntity' {
        It 'Initialize-VpnSettingsEntity' {
            # a simple test to create an object
            #$NewObject = Initialize-VpnSettingsEntity -Endpoint "TEST_VALUE" -Port "TEST_VALUE" -Parameters "TEST_VALUE" -Terms "TEST_VALUE" -Policy "TEST_VALUE"
            #$NewObject | Should -BeOfType VpnSettingsEntity
            #$NewObject.property | Should -Be 0
        }
    }
}
