=begin
#Lethean VPM

#Distributed Virtual Private Marketplace

The version of the OpenAPI document: 1
Contact: contact@lethean.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for LetheanVpm::ServicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServicesApi' do
  before do
    # run before each test
    @api_instance = LetheanVpm::ServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServicesApi' do
    it 'should create an instance of ServicesApi' do
      expect(@api_instance).to be_instance_of(LetheanVpm::ServicesApi)
    end
  end

  # unit tests for create
  # @param service_entity 
  # @param [Hash] opts the optional parameters
  # @return [ServiceEntity]
  describe 'create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_one
  # @param client 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'find_one test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
