// tslint:disable
/**
 * Lethean VPN Api
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProxySettingsEntity
 */
export interface ProxySettingsEntity {
    /**
     * IP Address of endpoints for Proxy service only
     * @type {string}
     * @memberof ProxySettingsEntity
     */
    endpoint: string;
    /**
     * Port available on endpoint
     * @type {string}
     * @memberof ProxySettingsEntity
     */
    port: string;
    /**
     * Terms for the service
     * @type {string}
     * @memberof ProxySettingsEntity
     */
    terms: string;
    /**
     * a JSON containing access policy - whitelist/blacklist default, allowed/blocked IPs and FQDNs in regex format. This is NOT sent to SDP. It is used by the Dispatcher to orchestrate restrictions on Server
     * @type {Array<string>}
     * @memberof ProxySettingsEntity
     */
    policy: Array<string>;
}
