--[[
  Lethean VPN Api
 
  Distributed Virtual Private Marketplace
 
  The version of the OpenAPI document: 1
  
  Generated by: https://openapi-generator.tech
]]

-- time_range_entity class
local time_range_entity = {}
local time_range_entity_mt = {
	__name = "time_range_entity";
	__index = time_range_entity;
}

local function cast_time_range_entity(t)
	return setmetatable(t, time_range_entity_mt)
end

local function new_time_range_entity(from, to)
	return cast_time_range_entity({
		["from"] = from;
		["to"] = to;
	})
end

return {
	cast = cast_time_range_entity;
	new = new_time_range_entity;
}
