# coding: utf-8

"""
    Lethean VPM

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from lethean_vpm.provider_api import ProviderApi  # noqa: E501
from openapi_client.rest import ApiException


class TestProviderApi(unittest.TestCase):
    """ProviderApi unit test stubs"""

    def setUp(self):
        self.api = lethean_vpm.provider_api.ProviderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_all(self):
        """Test case for find_all

        """
        pass


if __name__ == '__main__':
    unittest.main()
