/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TimeRangeEntity.h
 *
 * 
 */

#ifndef ORG_LTHN_VPM_CLIENT_MODEL_TimeRangeEntity_H_
#define ORG_LTHN_VPM_CLIENT_MODEL_TimeRangeEntity_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace lthn {
namespace vpm {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  TimeRangeEntity
    : public ModelBase
{
public:
    TimeRangeEntity();
    virtual ~TimeRangeEntity();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TimeRangeEntity members

    /// <summary>
    /// YYYY-MM-DDT00:00:00Z
    /// </summary>
    utility::datetime getFrom() const;
    bool fromIsSet() const;
    void unsetFrom();

    void setFrom(const utility::datetime& value);

    /// <summary>
    /// YYYY-MM-DDT00:00:00Z
    /// </summary>
    utility::datetime getTo() const;
    bool toIsSet() const;
    void unsetTo();

    void setTo(const utility::datetime& value);


protected:
    utility::datetime m_From;
    bool m_FromIsSet;
    utility::datetime m_To;
    bool m_ToIsSet;
};


}
}
}
}
}

#endif /* ORG_LTHN_VPM_CLIENT_MODEL_TimeRangeEntity_H_ */
