=begin
#Lethean VPN Api

#Distributed Virtual Private Marketplace

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TimeRangeEntity
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TimeRangeEntity do
  let(:instance) { OpenapiClient::TimeRangeEntity.new }

  describe 'test an instance of TimeRangeEntity' do
    it 'should create an instance of TimeRangeEntity' do
      expect(instance).to be_instance_of(OpenapiClient::TimeRangeEntity)
    end
  end
  describe 'test attribute "from"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
