=begin comment

Lethean VPN Api

Distributed Virtual Private Marketplace

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 2;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('WWW::OpenAPIClient::Object::ServiceEntity');

# uncomment below and update the test
#my $instance = WWW::OpenAPIClient::Object::ServiceEntity->new();
#
#isa_ok($instance, 'WWW::OpenAPIClient::Object::ServiceEntity');

