/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ProviderApi.h
 *
 * 
 */

#ifndef ORG_LTHN_VPM_CLIENT_API_ProviderApi_H_
#define ORG_LTHN_VPM_CLIENT_API_ProviderApi_H_


#include "../ApiClient.h"

#include "ServiceEntity.h"


#include <boost/optional.hpp>

namespace org {
namespace lthn {
namespace vpm {
namespace client {
namespace api {

using namespace org::lthn::vpm::client::model;



class  ProviderApi 
{
public:

    explicit ProviderApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ProviderApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<ServiceEntity>>> findAll(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}
}

#endif /* ORG_LTHN_VPM_CLIENT_API_ProviderApi_H_ */

