/**
 * Lethean VPM
 * Distributed Virtual Private Marketplace
 *
 * The version of the OpenAPI document: 1
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ServicesApi.h
 *
 * 
 */

#ifndef ORG_LTHN_VPM_CLIENT_API_ServicesApi_H_
#define ORG_LTHN_VPM_CLIENT_API_ServicesApi_H_


#include "../ApiClient.h"

#include "ServiceEntity.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace org {
namespace lthn {
namespace vpm {
namespace client {
namespace api {

using namespace org::lthn::vpm::client::model;



class  ServicesApi 
{
public:

    explicit ServicesApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ServicesApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="serviceEntity"></param>
    pplx::task<std::shared_ptr<ServiceEntity>> create(
        std::shared_ptr<ServiceEntity> serviceEntity
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="client"></param>
    pplx::task<utility::string_t> findOne(
        utility::string_t client
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<utility::string_t> list(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}
}

#endif /* ORG_LTHN_VPM_CLIENT_API_ServicesApi_H_ */

